### ISSUE TITLE
Incorrect ip recognition position

### ISSUE THREAD

**Issue by jerome2012** [oschwald/geoip2-golang#109]
<img width="784" alt="image" src="https://github.com/oschwald/geoip2-golang/assets/3930192/73b0081b-deca-4ad8-b44d-f7e393e76898">

IP: 152.190.52.66
{map[de:Nordamerika en:North America es:Norteamérica fr:Amérique du Nord ja:北アメリカ pt-BR:América do Norte ru:Северная Америка zh-CN:北美洲] NA 6255149} [] {map[]   0 false} {map[de:Vereinigte Staaten en:United States es:Estados Unidos fr:États Unis ja:アメリカ pt-BR:EUA ru:США zh-CN:美国] US 6252001 false} {map[de:Vereinigte Staaten en:United States es:Estados Unidos fr:États Unis ja:アメリカ pt-BR:EUA ru:США zh-CN:美国] US 6252001 false} {America/Chicago 37.751 -97.822 0 1000} {false false}}

**Comment by oschwald** [comment]
Please verify your database is up to date. If it is up to date and you are certain of the associated location, submit a correction for MaxMind for whichever database you are using.
