### ISSUE TITLE
Switch to ISC license

### ISSUE THREAD

**Issue by oschwald** [oschwald/geoip2-golang#11]
I would like to switch all the code in this library to the [ISC license](http://en.wikipedia.org/wiki/ISC_license). The reason for this is to make this library compatible with code that is licensed under the GPL v2.

@oxtoacart, @andrewlook, @sosedoff, and @GregBowyer, as you all contributed code to this library, would you confirm in this issue that this is acceptable to you? Thanks!

**Comment by awalterschulze** [comment]
What code that is under GPL v2 do you want to be compatible with?

**Comment by andrewlook** [comment]
@oschwald I'm not sure i fully understand what this means, but I'm just using this software internally - not planning on redistributing any code based on it, so this doesn't bother me at all.

**Comment by sosedoff** [comment]
im fine with license switch

**Comment by oschwald** [comment]
@andrewlook, the primary difference between the ISC license and the Apache 2 license is the express grant of any patent rights by contributors in the latter. Although I generally prefer having such a grant in the license, I don't think it makes sense for such a small library, especially when it comes at the cost of GPL v2 compatibility.

@awalterschulze, I noticed some users of this library are distributing their code under GPL v2+. While this is technically OK as Apache 2 is compatible with GPL v3, it sorts of puts them in an awkward situation where the effective license is GPL v3 despite the stated license. Also, I know of one project that had to reimplement a GeoIP2 database reader because their code is licensed under GPL v2 only. In relicensing, I hope to avoid such pointless efforts in the future.

**Comment by andrewlook** [comment]
@oschwald thanks, license switch is fine by me

**Comment by awalterschulze** [comment]
Aha makes a lot of sense :+1:
