### ISSUE TITLE
DP-IP & GeoIP2

### ISSUE THREAD

**Issue by MaurUppi** [oschwald/geoip2-golang#112]
I knew your `reader.go` supported both dbip  & MaxMind database format. 
but would you help me understand the method of recognition by the filename OR read the database schema to determine the format?

thx a lot!

**Comment by oschwald** [comment]
See [this function](https://github.com/oschwald/geoip2-golang/blob/fbe22892b33824e127ef49e61e84812d8d5497a6/reader.go#L277-L313). It checks `database_type` in the metadata.
