### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by gregoire-mullvad** [oschwald/geoip2-golang#120]
Hi! The latest release is 1.10.0 but the tag says v1.11.0. I guess that's just a typo but I was a bit confused by it so I thought I'd mention it in case you didn't notice.
Thanks for your work!

**Comment by oschwald** [comment]
Thanks! I hadn't noticed. It looks like I made a typo with the tag, skipping 1.10.0. I'll update the release notes to be clearer.
