### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bobbonomo** [oschwald/geoip2-golang#123]
go get github.com/oschwald/geoip2-golang

go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

go install github.com/oschwald/geoip2-golang@latest

package github.com/oschwald/geoip2-golang is not a main package

Tried on Windows and Linux

**Comment by oschwald** [comment]
This package is a library intended to be used in a Go application. It does not provide a standalone tool for doing lookups.
