### ISSUE TITLE
safe for access from multiple goroutines

### ISSUE THREAD

**Issue by mseshachalam** [oschwald/geoip2-golang#18]
I am developing an http api on top of this package. I am wondering if the db is safe to access from multiple goroutines.

https://github.com/mseshachalam/geoip/blob/master/main.go#L42 here for each api call i am opening the mmdb file. Is it okay if i open it in the outer scope i.e in the main function, something like this.

```
db, err := geoip2.Open("GeoLite2-City.mmdb")
defer db.Close()
router.GET("/ip/:ip", func(c *gin.Context) { })
```

**Comment by oschwald** [comment]
Yes, that is safe.
