### ISSUE TITLE
Instantiate a *geoip2.Reader from an io.Reader

### ISSUE THREAD

**Issue by nesv** [oschwald/geoip2-golang#20]
It would be handy if there was a way to create a new `*geoip2.Reader` from an `io.Reader`.

My rationale, is that to save a little bit of disk space, it would be nice to be able to store compressed versions of the databases, and load them by passing in a `compress/*gzip.Reader`, for example.

If you would like, I could code this up, and submit a pull request.

**Comment by oschwald** [comment]
A convenience function might be useful, but you can currently achieve this with:

```go
bytes, err := ioutil.ReadAll(ioReader)
...
db, err := geoip2.FromBytes(bytes)
```
