### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by satta** [oschwald/geoip2-golang#21]
I was wondering whether there will be a new release tagged anytime soon? There have been a few additions to the API and I would like to update the Debian packaged version, which currently tracks versioned releases.

**Comment by oschwald** [comment]
As with many Go projects, the tagged releases haven't meant much as `master` is kept in an always releasable state. I did tag new 1.0.0 releases though and I'll try to remember to do that in the future.

**Comment by satta** [comment]
Thanks! BTW I was going to ask the same for maxminddb-golang, which is currently at 0.2.0.

**Comment by oschwald** [comment]
I tagged that at 1.0.0 at the same time.

**Comment by satta** [comment]
Great, thanks again!
