### ISSUE TITLE
try to install geoip2 but got below message

### ISSUE THREAD

**Issue by webbhlin** [oschwald/geoip2-golang#28]
go get error:
go get github.com/oschwald/geoip2-golang
# github.com/oschwald/geoip2-golang
../github.com/oschwald/geoip2-golang/reader.go:320: r.mmdbReader.Close() used as value

**Comment by dgryski** [comment]
I think your maxminddb-golang repo is out of date:

https://github.com/oschwald/maxminddb-golang/commit/0656a7cd1b891bb0a07e9a0c818574e0353dbac5

Try
```
go get -v -u github.com/oschwald/geoip2-golang
```
