### ISSUE TITLE
Ability to look up city name using GeonameID

### ISSUE THREAD

**Issue by F21** [oschwald/geoip2-golang#29]
It is recommended to store the GeonameID for a city when storing this information in a database as the names of the city can change.

There doesn't appear to be a way to convert this GeonameID back into the name of the city.

It would be nice if the API provided a method to do this.

**Comment by oschwald** [comment]
There is not an efficient way to look up by GeoNameID in the database. If you need to do this, I would suggest using GeoNames data directly or perhaps using the MaxMind CSV.

**Comment by isometriq** [comment]
In case this helps someone, there is a 'get' service for a geonameid: 
http://ws.geonames.org/get?geonameId=6295630&style=full
