### ISSUE TITLE
how to see all cities and countries?

### ISSUE THREAD

**Issue by x8core** [oschwald/geoip2-golang#30]

**Comment by oschwald** [comment]
In order to do this, you would need to use `maxminddb`'s traversal feature. However, you likely would be better off getting the cities and countries from the CSV version of the database.

**Comment by nexcode** [comment]
```go
func (r *Reader) Decode(offset uintptr, result interface{}) error
```
This method?

**Comment by oschwald** [comment]
https://godoc.org/github.com/oschwald/maxminddb-golang#Reader.Networks
