### ISSUE TITLE
Lookup?

### ISSUE THREAD

**Issue by nicola-spb** [oschwald/geoip2-golang#33]
How can I do Lookup? 
maybe geoip2 should have func GetReader() for this?

**Comment by oschwald** [comment]
I am not clear on what you are trying to do.

**Comment by nicola-spb** [comment]
I wanna get some fields: timezone, lan and lon without other fields. Can I do it with geo2 or I should use maxminddb-golang?

**Comment by oschwald** [comment]
If you want to minimize the amount of data looked up, you should use `maxminddb`. `geoip2` is a higher level API that returns a struct with all the data.

**Comment by nicola-spb** [comment]
ok. Thanks.
