### ISSUE TITLE
reader.ASN broken?

### ISSUE THREAD

**Issue by sersh88** [oschwald/geoip2-golang#50]
Tried to use free geolite2 ASN database, but it always return error:

`the MaxMind DB file's data section contains bad data (float 64 size of 25)`

Tried to re-download, tried different IP's - same error. For example, with IP `8.8.8.8`.
No issues with city and country databases.

**Comment by sersh88** [comment]
Looks like it's only under OS X ( at least high sierra ). No issues in Linux.

**Comment by oschwald** [comment]
This sounds like a corrupt database to me. I'd suggest checking the MD5 of the decompressed MMDB file to ensure it matches what you expect.

**Comment by oschwald** [comment]
The unit tests now run on macOS, including the ASN one. Given that the code to read the ASN database is the same as the City and Country databases, it seems unlikely that there is an issue there. I would need more particulars about the exact ASN database file exhibiting the issue, such as the database date and the MD5 of the file to debug this further.
