### ISSUE TITLE
Add go module support

### ISSUE THREAD

**Issue by euskadi31** [oschwald/geoip2-golang#52]

**Comment by oschwald** [comment]
Is there a particular reason why you want this?

**Comment by Dreamacro** [comment]
actually, go module become the de facto standard. Is there a particular reason why we don't migrate to the go module?

**Comment by oschwald** [comment]
There is minimal benefit to switching this repo to Go modules. The releases are tagged using SemVer and work fine in applications using Go modules. There is one dependency that is co-maintained with this so any benefit of versioning dependencies is quite limited.

Although I use Go modules daily, there are still issues with them that crop up from time to time and changing this repo to use Go modules will likely break someone's workflow.
