### ISSUE TITLE
Database specific methods should check database type

### ISSUE THREAD

**Issue by fnkr** [oschwald/geoip2-golang#6]
I can't get ISP infos, I always get an empty result:
```json
{
        "AutonomousSystemNumber": 0,
        "AutonomousSystemOrganization": "",
        "ISP": "",
        "Organization": ""
}
```

Script:
```go
package main

import (
	"fmt"
	"net"
	"encoding/json"
	"github.com/oschwald/geoip2-golang"
)

var db, err = geoip2.Open("GeoLite2-Country.mmdb")

func p(input interface{}) {
	var output []byte
	output, _ = json.MarshalIndent(input, "", "	")
	fmt.Println(string(output))
}

func main() {
	ip := "8.8.8.8"

	if err != nil {
		fmt.Println(err.Error())
	}

	recordCity, err := db.City(net.ParseIP(ip))
	if err != nil {
		fmt.Println(err.Error())
	}

	recordISP, err := db.ISP(net.ParseIP(ip))
	if err != nil {
		fmt.Println(err.Error())
	}

	p(recordCity)
	p(recordISP)
}
```
Output: https://gist.github.com/fnkr/68a6726ae544435a4061#file-output-json-L69-L74

**Comment by oschwald** [comment]
You need to use the ISP database to get ISP information. The country database does not contain this.

I am leaving this issue open as the API should return an error when the wrong database type is used.

**Comment by fnkr** [comment]
Where can I download the ISP Database? [This page](http://dev.maxmind.com/geoip/geoip2/geolite2/) only lists the City and Country databases.

**Comment by oschwald** [comment]
There isn't a GeoLite2 version. Unfortunately there is only the [commercial version](https://www.maxmind.com/en/geoip2-isp-database).
