### ISSUE TITLE
CIDR Support

### ISSUE THREAD

**Issue by NitroCao** [oschwald/geoip2-golang#64]
It seems that the current version doesn't support getting the CIDR of an IP. Do we have any plans?

**Comment by NitroCao** [comment]
Sorry to bother you. I just read the code and add the method. Maybe you need to update the module 😄

**Comment by oschwald** [comment]
Do you mean the network associated with the IP in the database? You can easily do this using `maxminddb.LookupNetwork` along with the models from this package. Is there a particular reason you need this? I am not sure it is worth including by default given that it will involve extra allocations for what seems like fairly specialized information.

**Comment by NitroCao** [comment]
> Do you mean the network associated with the IP in the database? You can easily do this using `maxminddb.LookupNetwork` along with the models from this package. Is there a particular reason you need this? I am not sure it is worth including by default given that it will involve extra allocations for what seems like fairly specialized information.

Yeah, the CIDR is important for me. I've already implemented the method through `LookupNetwork`. Maybe you just add the method and let users choose which method to use. It's just a suggestion of course 👍
