### ISSUE TITLE
mmdb export to csv or to dat

### ISSUE THREAD

**Issue by davidka79** [oschwald/geoip2-golang#74]
Hello, I have made changes at mmdb file with geoip2-golang, is ther any way to convert mmdb to csv or to export to csv or direct to dat file? Out F5 Load balancers understands only old dat fiiles

**Comment by oschwald** [comment]
You could export it to CSV by iterating over by using the [networks iterator on `maxminddb`](https://pkg.go.dev/github.com/oschwald/maxminddb-golang?utm_source=godoc#Networks). As far as converting it to the legacy format, there are several third party tools for that, but I don't have any experience with them.
