### ISSUE TITLE
Exporting getDBType, databaseType and isTYPE constants

### ISSUE THREAD

**Issue by snebel29** [oschwald/geoip2-golang#76]
I was thinking that would be handy to export `getDBType`, `databaseType` and the isTYPE constants to help users discovering databases schema without having to query the databases and looking for `InvalidMethodError` errors, Would such change be accepted?

**Comment by oschwald** [comment]
I think I'd prefer to leave the method and constants internal so that they can change as needed and don't create a confusing API. If you are not sure what database you are opening at runtime, you can always use the `Metadata()` to get the database type.

**Comment by snebel29** [comment]
ok, thanks.
