### ISSUE TITLE
Issue with Go 1.18

### ISSUE THREAD

**Issue by leearmstrong** [oschwald/geoip2-golang#82]
Since upgrading to Go 1.18 I have an issue similar to https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus

Can you publish a new version with the new [deps update](https://github.com/oschwald/geoip2-golang/commit/3ec04f3d9debce9390e62a077c40c2347d56e189) you did?

Thank you

**Comment by oschwald** [comment]
Thanks. I did this.

**Comment by leearmstrong** [comment]
👏
