### ISSUE TITLE
For GeoLite2-ASN.mmdb: query organization name with known ASN

### ISSUE THREAD

**Issue by ojdo** [oschwald/geoip2-golang#89]
Currenty I only retrieve the `AutonomousSystemNumber uint` at one point in a longer date pipeline which aggregates over multiple IPs. Is there a "decent" way to query the database with the above number and return the corresponding `AutonomousSystemOrganization string`?

I would be fine with just iterating over the whole file, but so far I only could identify the [`Networks`-oriented traverse](https://github.com/oschwald/maxminddb-golang/blob/main/traverse.go) functionality.

Is there an elegant way to accomplish this?

**Comment by oschwald** [comment]
No, there isn't a way to query by ASN. The database is only indexed by IP address. As you suggest, you can use the `Networks` function to (inefficiently) create such a map yourself using something like `db.Networks(maxminddb.SkipAliasedNetworks)`.
